apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: pipeline
  name: pipeline
  namespace: default
spec:
  selector:
    matchLabels:
      app: pipeline
  template:
    metadata:
      labels:
        app: pipeline
    spec:
      containers:
      - image: gcr.io/devops-training-2/pipeline:c210e7257ddfaaf517a1e4620ee4d9c023e365a2
        name: pipeline
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
